name: Release

on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/python-binexport
    permissions:
      # Used to publish to PyPI with Trusted Publishing.
      id-token: write
      # Used for uploading the release notes.
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Show what was built
        run: ls -la dist/        # diagnose issue

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          attestations: true

      - name: Upload packages to the GitHub release
        uses: softprops/action-gh-release@v3.0.1
        with:
          files: dist/*
