name: Release

on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  build_wheel_and_sdist:
    name: Build wheel and tar.gz
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install build
      - name: Build wheel and sdist
        run: python -m build
      - uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: |
            ./dist/python_binexport*.whl
            ./dist/*.tar.gz

  upload_pypi:
    needs: build_wheel_and_sdist
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/python-binexport
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: artifact
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist/
          attestations: true

      - name: Upload Python packages for release notes
        uses: softprops/action-gh-release@v3.0.1
        with:
          files: |
            dist/*
